// <auto-generated />
using System;
using CafeManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CafeManagement.Migrations
{
    [DbContext(typeof(CafeDbContext))]
    [Migration("20260502232636_AddCategoryColor")]
    partial class AddCategoryColor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CafeManagement.Models.CafeTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TableNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CafeTables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 2,
                            Status = 0,
                            TableNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 4,
                            Status = 0,
                            TableNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 2,
                            Status = 0,
                            TableNumber = 3
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 6,
                            Status = 0,
                            TableNumber = 4
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 4,
                            Status = 0,
                            TableNumber = 5
                        });
                });

            modelBuilder.Entity("CafeManagement.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("CafeManagement.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CategoryColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageEmoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasDiscriminator<string>("ItemType").HasValue("MenuItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CafeManagement.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DiscountApplied")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsWalkIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TableId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CafeManagement.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("CafeManagement.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CafeManagement.Models.Beverage", b =>
                {
                    b.HasBaseType("CafeManagement.Models.MenuItem");

                    b.Property<int>("CaffeineLevel")
                        .HasColumnType("integer");

                    b.Property<bool>("IsHot")
                        .HasColumnType("boolean");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Beverage");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Beverage",
                            CategoryColor = "#6c757d",
                            CreatedAt = new DateTime(2026, 5, 2, 23, 26, 36, 396, DateTimeKind.Utc).AddTicks(1390),
                            Description = "Rich and bold single shot",
                            ImageEmoji = "☕",
                            ImageUrl = "/images/menu/beverages/Espresso.png",
                            IsAvailable = true,
                            Name = "Espresso",
                            Price = 180m,
                            CaffeineLevel = 95,
                            IsHot = true,
                            Size = "Medium"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Beverage",
                            CategoryColor = "#6c757d",
                            CreatedAt = new DateTime(2026, 5, 2, 23, 26, 36, 396, DateTimeKind.Utc).AddTicks(1400),
                            Description = "Vanilla milk and espresso with caramel",
                            ImageEmoji = "🥤",
                            ImageUrl = "/images/menu/beverages/Caramel Macchiato.png",
                            IsAvailable = true,
                            Name = "Caramel Macchiato",
                            Price = 320m,
                            CaffeineLevel = 150,
                            IsHot = true,
                            Size = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Beverage",
                            CategoryColor = "#6c757d",
                            CreatedAt = new DateTime(2026, 5, 2, 23, 26, 36, 396, DateTimeKind.Utc).AddTicks(1410),
                            Description = "Premium grade Japanese matcha",
                            ImageEmoji = "🍵",
                            ImageUrl = "/images/menu/beverages/Matcha Latte.png",
                            IsAvailable = true,
                            Name = "Matcha Latte",
                            Price = 350m,
                            CaffeineLevel = 70,
                            IsHot = true,
                            Size = "Medium"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Beverage",
                            CategoryColor = "#6c757d",
                            CreatedAt = new DateTime(2026, 5, 2, 23, 26, 36, 396, DateTimeKind.Utc).AddTicks(1410),
                            Description = "Creamy Belgian cocoa with marshmallows",
                            ImageEmoji = "🍫",
                            ImageUrl = "/images/menu/beverages/Hot Chocolate.png",
                            IsAvailable = true,
                            Name = "Hot Chocolate",
                            Price = 280m,
                            CaffeineLevel = 5,
                            IsHot = true,
                            Size = "Medium"
                        });
                });

            modelBuilder.Entity("CafeManagement.Models.Dessert", b =>
                {
                    b.HasBaseType("CafeManagement.Models.MenuItem");

                    b.Property<string>("Allergens")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Calories")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSeasonalItem")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("Dessert");

                    b.HasData(
                        new
                        {
                            Id = 9,
                            Category = "Dessert",
                            CategoryColor = "#6c757d",
                            CreatedAt = new DateTime(2026, 5, 2, 23, 26, 36, 396, DateTimeKind.Utc).AddTicks(1450),
                            Description = "Italian coffee-flavored dessert",
                            ImageEmoji = "🍰",
                            ImageUrl = "/images/menu/desserts/Tiramisu.png",
                            IsAvailable = true,
                            Name = "Tiramisu",
                            Price = 400m,
                            Allergens = "None",
                            Calories = 450,
                            IsSeasonalItem = false
                        },
                        new
                        {
                            Id = 10,
                            Category = "Dessert",
                            CategoryColor = "#6c757d",
                            CreatedAt = new DateTime(2026, 5, 2, 23, 26, 36, 396, DateTimeKind.Utc).AddTicks(1450),
                            Description = "New York style baked cheesecake",
                            ImageEmoji = "🥧",
                            ImageUrl = "/images/menu/desserts/Blueberry Cheesecake.png",
                            IsAvailable = true,
                            Name = "Blueberry Cheesecake",
                            Price = 450m,
                            Allergens = "None",
                            Calories = 520,
                            IsSeasonalItem = false
                        },
                        new
                        {
                            Id = 11,
                            Category = "Dessert",
                            CategoryColor = "#6c757d",
                            CreatedAt = new DateTime(2026, 5, 2, 23, 26, 36, 396, DateTimeKind.Utc).AddTicks(1450),
                            Description = "Warm fudge brownie with vanilla scoop",
                            ImageEmoji = "🍨",
                            ImageUrl = "/images/menu/desserts/Brownie with Ice Cream.png",
                            IsAvailable = true,
                            Name = "Brownie with Ice Cream",
                            Price = 350m,
                            Allergens = "None",
                            Calories = 600,
                            IsSeasonalItem = false
                        },
                        new
                        {
                            Id = 12,
                            Category = "Dessert",
                            CategoryColor = "#6c757d",
                            CreatedAt = new DateTime(2026, 5, 2, 23, 26, 36, 396, DateTimeKind.Utc).AddTicks(1450),
                            Description = "Box of 6 colorful French macarons",
                            ImageEmoji = "🥯",
                            ImageUrl = "/images/menu/desserts/Macarons Box.png",
                            IsAvailable = true,
                            Name = "Macarons Box",
                            Price = 600m,
                            Allergens = "None",
                            Calories = 300,
                            IsSeasonalItem = false
                        });
                });

            modelBuilder.Entity("CafeManagement.Models.Food", b =>
                {
                    b.HasBaseType("CafeManagement.Models.MenuItem");

                    b.Property<bool>("IsVegetarian")
                        .HasColumnType("boolean");

                    b.Property<int>("PreparationTimeMinutes")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Food");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Category = "Food",
                            CategoryColor = "#6c757d",
                            CreatedAt = new DateTime(2026, 5, 2, 23, 26, 36, 396, DateTimeKind.Utc).AddTicks(1430),
                            Description = "Sourdough bread with poached eggs",
                            ImageEmoji = "🥑",
                            ImageUrl = "/images/menu/food/Avocado Toast.png",
                            IsAvailable = true,
                            Name = "Avocado Toast",
                            Price = 450m,
                            IsVegetarian = true,
                            PreparationTimeMinutes = 15
                        },
                        new
                        {
                            Id = 6,
                            Category = "Food",
                            CategoryColor = "#6c757d",
                            CreatedAt = new DateTime(2026, 5, 2, 23, 26, 36, 396, DateTimeKind.Utc).AddTicks(1430),
                            Description = "Juicy chicken breast with house sauce",
                            ImageEmoji = "🍔",
                            ImageUrl = "/images/menu/food/Grilled Chicken Burger.png",
                            IsAvailable = true,
                            Name = "Grilled Chicken Burger",
                            Price = 380m,
                            IsVegetarian = false,
                            PreparationTimeMinutes = 15
                        },
                        new
                        {
                            Id = 7,
                            Category = "Food",
                            CategoryColor = "#6c757d",
                            CreatedAt = new DateTime(2026, 5, 2, 23, 26, 36, 396, DateTimeKind.Utc).AddTicks(1430),
                            Description = "Classic white sauce pasta with mushrooms",
                            ImageEmoji = "🍝",
                            ImageUrl = "/images/menu/food/Pasta Alfredo.png",
                            IsAvailable = true,
                            Name = "Pasta Alfredo",
                            Price = 550m,
                            IsVegetarian = true,
                            PreparationTimeMinutes = 15
                        },
                        new
                        {
                            Id = 8,
                            Category = "Food",
                            CategoryColor = "#6c757d",
                            CreatedAt = new DateTime(2026, 5, 2, 23, 26, 36, 396, DateTimeKind.Utc).AddTicks(1430),
                            Description = "Three-layered sandwich with turkey and egg",
                            ImageEmoji = "🥪",
                            ImageUrl = "/images/menu/food/Club Sandwich.png",
                            IsAvailable = true,
                            Name = "Club Sandwich",
                            Price = 420m,
                            IsVegetarian = false,
                            PreparationTimeMinutes = 15
                        });
                });

            modelBuilder.Entity("CafeManagement.Models.Snack", b =>
                {
                    b.HasBaseType("CafeManagement.Models.MenuItem");

                    b.Property<bool>("IsCrunchy")
                        .HasColumnType("boolean");

                    b.Property<string>("PortionSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Snack");

                    b.HasData(
                        new
                        {
                            Id = 13,
                            Category = "Snack",
                            CategoryColor = "#6c757d",
                            CreatedAt = new DateTime(2026, 5, 2, 23, 26, 36, 396, DateTimeKind.Utc).AddTicks(1470),
                            Description = "Salted golden fries with dip",
                            ImageEmoji = "🍟",
                            ImageUrl = "/images/menu/snacks/Crispy French Fries.png",
                            IsAvailable = true,
                            Name = "Crispy French Fries",
                            Price = 220m,
                            IsCrunchy = false,
                            PortionSize = "Regular"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Snack",
                            CategoryColor = "#6c757d",
                            CreatedAt = new DateTime(2026, 5, 2, 23, 26, 36, 396, DateTimeKind.Utc).AddTicks(1470),
                            Description = "Corn chips with cheese and salsa",
                            ImageEmoji = "🌮",
                            ImageUrl = "/images/menu/snacks/Nachos Supreme.png",
                            IsAvailable = true,
                            Name = "Nachos Supreme",
                            Price = 380m,
                            IsCrunchy = false,
                            PortionSize = "Shareable"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Snack",
                            CategoryColor = "#6c757d",
                            CreatedAt = new DateTime(2026, 5, 2, 23, 26, 36, 396, DateTimeKind.Utc).AddTicks(1470),
                            Description = "Beer-battered crispy onion rings",
                            ImageEmoji = "🧅",
                            ImageUrl = "/images/menu/snacks/Onion Rings.png",
                            IsAvailable = true,
                            Name = "Onion Rings",
                            Price = 250m,
                            IsCrunchy = false,
                            PortionSize = "Regular"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Snack",
                            CategoryColor = "#6c757d",
                            CreatedAt = new DateTime(2026, 5, 2, 23, 26, 36, 396, DateTimeKind.Utc).AddTicks(1470),
                            Description = "Spicy buffalo wings (6 pieces)",
                            ImageEmoji = "🍗",
                            ImageUrl = "/images/menu/snacks/Chicken Wings.png",
                            IsAvailable = true,
                            Name = "Chicken Wings",
                            Price = 480m,
                            IsCrunchy = false,
                            PortionSize = "Regular"
                        });
                });

            modelBuilder.Entity("CafeManagement.Models.Special", b =>
                {
                    b.HasBaseType("CafeManagement.Models.MenuItem");

                    b.Property<DateTime>("AvailableUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LimitedEditionNote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Special");

                    b.HasData(
                        new
                        {
                            Id = 17,
                            Category = "Special",
                            CategoryColor = "#6c757d",
                            CreatedAt = new DateTime(2026, 5, 2, 23, 26, 36, 396, DateTimeKind.Utc).AddTicks(1490),
                            Description = "12-hour steeped artisan coffee",
                            ImageEmoji = "🧊",
                            ImageUrl = "/images/menu/specials/Signature Cold Brew.png",
                            IsAvailable = true,
                            Name = "Signature Cold Brew",
                            Price = 380m,
                            AvailableUntil = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LimitedEditionNote = "Summer Favorite"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Special",
                            CategoryColor = "#6c757d",
                            CreatedAt = new DateTime(2026, 5, 2, 23, 26, 36, 396, DateTimeKind.Utc).AddTicks(1490),
                            Description = "Hand-tossed dough with premium toppings",
                            ImageEmoji = "🍕",
                            ImageUrl = "/images/menu/specials/Chef's Pizza.png",
                            IsAvailable = true,
                            Name = "Chef's Pizza",
                            Price = 850m,
                            AvailableUntil = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LimitedEditionNote = "Limited Supply"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Special",
                            CategoryColor = "#6c757d",
                            CreatedAt = new DateTime(2026, 5, 2, 23, 26, 36, 396, DateTimeKind.Utc).AddTicks(1490),
                            Description = "Fragrant rose syrup with espresso",
                            ImageEmoji = "🌹",
                            ImageUrl = "/images/menu/specials/Iced Rose Latte.png",
                            IsAvailable = true,
                            Name = "Iced Rose Latte",
                            Price = 390m,
                            AvailableUntil = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LimitedEditionNote = "Exclusive"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Special",
                            CategoryColor = "#6c757d",
                            CreatedAt = new DateTime(2026, 5, 2, 23, 26, 36, 396, DateTimeKind.Utc).AddTicks(1490),
                            Description = "Molten center matcha cake",
                            ImageEmoji = "🍵",
                            ImageUrl = "/images/menu/specials/Matcha Lava Cake.png",
                            IsAvailable = true,
                            Name = "Matcha Lava Cake",
                            Price = 450m,
                            AvailableUntil = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LimitedEditionNote = "Spring Special"
                        });
                });

            modelBuilder.Entity("CafeManagement.Models.Order", b =>
                {
                    b.HasOne("CafeManagement.Models.CafeTable", "Table")
                        .WithMany()
                        .HasForeignKey("TableId");

                    b.HasOne("CafeManagement.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId");

                    b.Navigation("Table");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CafeManagement.Models.OrderItem", b =>
                {
                    b.HasOne("CafeManagement.Models.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeManagement.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CafeManagement.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("CafeManagement.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
